# Generated by Django 3.0.5 on 2021-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeStream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
