# Generated by Django 3.0.5 on 2021-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeStream', '0002_auto_20210209_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.URLField(),
        ),
    ]
